name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload site files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./  # Root folder

  deploy:
    needs: build
    runs-on: self-hosted
    environment:
      name: github-pages
      url: https://www.nainovate.ai
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
